version: '3.7'
services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - '9980:9980'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=base
      - POSTGRES_USER=adm
      - POSTGRES_PASSWORD=9mRE

